name: Build and Package Java App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Use your desired Java version
          distribution: 'temurin'

      # Step 3: Build JAR file with Maven (run from the root directory where pom.xml is)
      - name: Build JAR with Maven
        run: mvn clean package

      # Step 4: Download and install Launch4j
      - name: Download and install Launch4j
        run: |
          wget https://cyfuture.dl.sourceforge.net/project/launch4j/launch4j-3/3.50/launch4j-3.50-linux-x64.tgz?viasf=1 -O launch4j-3.50-linux-x64.tgz
          tar -xvzf launch4j-3.50-linux-x64.tgz
          sudo mkdir -p /usr/local/launch4j
          sudo mv launch4j/* /usr/local/launch4j/
          sudo ln -s /usr/local/launch4j/launch4j /usr/local/bin/launch4j
          # Convert launch4j script to Unix line endings
          sed -i 's/\r$//' /usr/local/bin/launch4j

      # Step 5: Convert JAR to EXE
      - name: Convert to EXE
        run: |
          mkdir -p output
          launch4j launch4j-config.xml

      # Step 6: Upload EXE as GitHub Artifact
      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: LTEBandControlApp
          path: output/LTEBandControlApp.exe
